### ISSUE TITLE
Comments on the bugfixes in ox-texinfo+

### ISSUE THREAD

**Issue by jleechpe** [tarsius/ox-texinfo-plus#1]
I was pointed towards this by https://github.com/magit/magit/issues/1645#issuecomment-84639130

@tarsius With regards to the `org-texinfo` exported, I was the author although I have not had the opportunity to update it with any new changes.

The crossreferences issue should be a limited issue in this case.  Every single link will be exported either as `@ref` or as `@uref` (specifically for URLs).  Unfortunately I can't catch the situation @npostavs mentioned (because of how Info itself parses the link) but it will never insert unwanted `see`'s.  If you need a `see` (or x/pxref) you will need to include it independently.

I only really looked at the bugfixes in your `texinfo+` because they would be most relevant (the additions are for Magit and so would be a modification to the exporter for that use).

The empty TODO does not appear to be an issue, I just tested on `Org-mode version beta_8.3 (beta_8.3-29-g126e2b.dirty @ c:/Users/jonpe/build/org/lisp/)` and TODO and non-TODO headlines all retain the correct spacings.

The use of `org-element-normalize-strings` should not remove any necessary newlines since it will only be touching the actual headlines, which should not include newlines (since they cannot in Org).  I believe I had originally inserted it to catch trailing newlines/spacing in headlines to allow for cleaner output.

Have you had any particular issues that needed those changes to be applied (with the base exporter and not due to added features for Magit)?

**Comment by tarsius** [comment]
Uh... sorry for the delay. Just wanted to say that I still intend to get back to you on this, but probably not anytime soon. ;-/

**Comment by tarsius** [comment]
I've decided to keep patching the exporter instead of trying to get my changes upstream, at least for the next few months.
